version: "3.4"
services:
 runtime-config:
  image: marochan442/filmlebendczil-runtime-config-server
  hostname:
   - runtime-config
  ports:
   - "8761:8761"
  expose:
   - 8761
  

 rating-management:
  image: marochan442/filmlebendczil-rating-management
  environment: 
   # Important for clients to register with eureka
   - eureka.client.serviceUrl.defaultZone=http://runtime-config:8761/
  ports:
   - "3333:3333"
  expose:
   - 3333 
  links:
   - runtime-config
  depends_pn:
   - runtime-config
   - data-access

 data-access:
  image: marochan442/filmlebendczil-da
  environment: 
   # Important for clients to register with eureka
   - eureka.client.serviceUrl.defaultZone=http://runtime-config:8761/
  ports:
   - "8080:8080"
   expose:
    - 8080
  links:
   - runtime-config
  depends_on:
   - runtime-config

  